[project]
name = "large-scale-classification"
version = "0.1.0"
description = "A walkthrough for building a large-scale text classifier"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "python-dotenv>=1.1.0",
]